### ISSUE TITLE
TypeScript type declaration file

### ISSUE THREAD

**Issue by geopic** [bbialke/flight-data#1]
If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

**Comment by bbialke** [comment]
That'd be great, thank you so much!

**Comment by bbialke** [comment]
@geopic feel free to submit a PR when you’re ready

**Comment by geopic** [comment]
I'll get started on it soon :smile:
